### PR TITLE
Add more thorough testing

### PR DESCRIPTION
**Pull request by philipwastakenwastaken**
This PR adds support for testing from local .html files. The current html files used are directly saved from actual websites. There are 6 test sites in the first commit, which are all news articles. It was also needed to support reading html from files from the library. 

There are a few considerations to make here:

1. Where should the `html` test files be saved? Some can be more than 1MB. A few can be manually trimmed down, but there is a risk of destroying the layout which `webpage` needs.
2. Some websites work fine when generating from the URL, but fail when generating directly from HTML.
3. We can only provide `OpenGraph` tests until #13 is merged. ~I suggest waiting for #13 before merging this PR.~ **Update:** Merged.
4. ~Writing the tests is cumbersome. I think there is a good solution to this, but I haven't tried it yet.~
5. There should be many more tests in the future. I don't think this PR should aim to be expansive. Therefore, I don't think that #8 should be closed even after merging this PR. We can always add more tests in later PRs.
6. I have no idea what to name the tests, they are just enumerated for now (e.g. `opengraph_1`, `opengraph_2`).

### CODE REVIEW

**Comment by philipwastakenwastaken** [comment]
While running the tests, I actually found a new `OpenGraph` key named `updated_time`. I have added it to our list of attribute keys.

**Comment by philipwastakenwastaken** [comment]
I have provided a function that makes testing much easier. Here is an example of a test case with the new code: 
```Rust
#[test]
fn opengraph_1() {
    // HTML file to test
    let path = "./tests/data/Ledende universitetsrektorers holdninger til antisemitisme udløser ramaskrig i USA - politiken.dk.html";

    // Define the attributes to be tested
    let expected_title = Attribute::Title(
        "Ledende universitetsrektorers holdninger til antisemitisme udløser ramaskrig i USA"
            .to_string(),
    );
    let expected_url = Attribute::Url("https://politiken.dk/internationalt/art9658207/Ledende-universitetsrektorers-holdninger-til-antisemitisme-udl%C3%B8ser-ramaskrig-i-USA".to_string());
    let expected_site = Attribute::Site("Politiken".to_string());

    let test_attributes = vec![expected_title, expected_url, expected_site];

    // Testing is done here
    opengraph_test(path, test_attributes);
}
```

**Comment by BX326** [comment]
Regarding the potentially large .html files used in testing, I'm leaning towards trimming them down to contain only what's relevant in terms of metadata. In addition to reducing the repository size, it'll also make them more readable which is useful when investigating failing tests. This means that we'll steer a bit a way from the actual real world website examples, but I don't think that's a problem as it's unrealistic to cover all types and structures of .html documents in our tests anyway. I think the goal should be to create small, contrived .html documents *based on* various actual online resources.

Regarding the second point about .html vs URL, that's something we have to figure out how to handle -- and look into whether it's a problem with the webpage crate.

**Comment by philipwastakenwastaken** [comment]
> Regarding the second point about .html vs URL, that's something we have to figure out how to handle -- and look into whether it's a problem with the webpage crate.

I suspect it has to do with how I actually saved the `html` files. My workflow was as follows:
1. Open a given URL
2. Right click and select `save as` to save the `html`. 

I believe that the `html` generated directly from the URL and by saving through the browser are not identical. So in a sense I think it is an easy fix.

**Comment by philipwastakenwastaken** [comment]
> Regarding the potentially large .html files used in testing, I'm leaning towards trimming them down to contain only what's relevant in terms of metadata. In addition to reducing the repository size, it'll also make them more readable which is useful when investigating failing tests. This means that we'll steer a bit a way from the actual real world website examples, but I don't think that's a problem as it's unrealistic to cover all types and structures of .html documents in our tests anyway. I think the goal should be to create small, contrived .html documents _based on_ various actual online resources.

I think this is an OK solution. The argument about readability is especially convincing and should be a priority.

**Comment by philipwastakenwastaken** [comment]
I've been toying with the idea using a more data-oriented approach to testing that involves as little code as possible when adding tests. I want it to be easy and seamless to add new test cases, even when several different parser are involved.

Say that we have the following file structure in the `tests` directory:

```.
│── integration.rs
│── data
      └── case1
            └── input.html
            └── expected.yml
```

i.e., every `html` test file has an associated `yml` file of expected attributes. Technically `json` is also possible, but I think that `yml` is much easier to write and read. An example of `expected.yml` could be:

```yml
all:
  title: "Ledende universitetsrektorers holdninger til antisemitisme udløser ramaskrig i USA"
  site: "Politiken"
opengraph:
  url: "https://politiken.dk/internationalt/art9658207/Ledende-universitetsrektorers-holdninger-til-antisemitisme-udl%C3%B8ser-ramaskrig-i-USA"
  locale: "da_DK"
schema_org:
  author: "Søren Astrup"
  date: "2023-12-11"
```


Notably, we have the `all` field. This field means that *every* parser expects this value for the given attribute. The remaning fields are attributes that are specific to a given metadata type. In this example, only `opengraph` has a tag for an URL. On the other hand, only `schema.org` has a tag for author and date.

A single test function then walks the `data` directory and runs all tests found, reminiscient of [How to Test](https://matklad.github.io/2021/05/31/how-to-test.html) by `matklad`.

I think this setup can be achieved with less than 100 lines or code, perhaps even less. It would certainly make it more convenient to write tests in the future, and especially if we start including more parsers.

EDIT:
Upon further consideration I'm not sure that the `all` field is such a good idea. It makes sense right with only two parsers implemented, since every website almost always has `opengraph` and one `schema.org` format. Perhaps we could have an additional field `schema_org_data_format` (e.g. `json-ld` or `microdata`) that specifices the format used for `schema.org`.

**Review by BX326 — APPROVED** [review]
Nice work. Now that I've reduced the HTML samples (to be more readable and at most a few kB in size), I'll merge this one. While there's still work to be done testing-wise, I think this data-driven setup is a good starting point for us.

**Pull request merged**
